// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrailerTicketSystem.Data;

#nullable disable

namespace TrailerTicketSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122155319_AddPasswordHashAndRole")]
    partial class AddPasswordHashAndRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrailerTicketSystem.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.Ticket", b =>
                {
                    b.Property<int>("TrailerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("FixNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("FixedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportNote")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TrailerId", "ReportedAt");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MechanicId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.Trailer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("StateId");

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.Ticket", b =>
                {
                    b.HasOne("TrailerTicketSystem.Models.AppUser", "Author")
                        .WithMany("TicketsAuthored")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TrailerTicketSystem.Models.AppUser", "Mechanic")
                        .WithMany("TicketsRepaired")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TrailerTicketSystem.Models.Trailer", "Trailer")
                        .WithMany("Tickets")
                        .HasForeignKey("TrailerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Mechanic");

                    b.Navigation("Trailer");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.Trailer", b =>
                {
                    b.HasOne("TrailerTicketSystem.Models.State", "State")
                        .WithMany("Trailers")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.AppUser", b =>
                {
                    b.Navigation("TicketsAuthored");

                    b.Navigation("TicketsRepaired");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.State", b =>
                {
                    b.Navigation("Trailers");
                });

            modelBuilder.Entity("TrailerTicketSystem.Models.Trailer", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
